### ISSUE TITLE
fix docker-based installation tests on Github actions

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#215]
see https://github.com/aiidateam/aiida-registry/pull/210 (running them locally works fine)

Once this is fixed, the information gathered this way can be used for a more detailed "workflow registry page"

**Comment by ltalirz** [comment]
The error messages vary; also have seen

```
- aiida-QECpWorkChain
   - Starting container for aiida-QECpWorkChain
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/models.py", line [9](https://github.com/aiidateam/aiida-registry/runs/5599530712?check_suite_focus=true#step:8:9)60, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.[12](https://github.com/aiidateam/aiida-registry/runs/5599530712?check_suite_focus=true#step:8:12)/x64/lib/python3.8/site-packages/docker/models/containers.py", line 8[19](https://github.com/aiidateam/aiida-registry/runs/5599530712?check_suite_focus=true#step:8:19), in run
    container = self.create(image=image, command=command,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/docker/models/containers.py", line 878, in create
Error: No space left on device : '/home/runner/runners/2.288.1/_diag/pages/e824c49b-4d8d-45e8-8eba-c77886be4d86_685b72c3-607b-5549-a738-905b3d9de4d7_1.log'
```

**Comment by ltalirz** [comment]
perhaps look how `molecule` is doing things under the hood, since this (creating & destroying docker containers, installing stuff on them) is exactly what is happening when the various ansible roles are being tested

**Comment by ltalirz** [comment]
Hm... maybe I missed the last line of the error message before?

``` 
Error: No space left on device : '/home/runner/runners/2.288.1/_diag/pages/e824c49b-4d8d-45e8-8eba-c77886be4d86_685b72c3-607b-5549-a738-905b3d9de4d7_1.log'
``` 

If the container is not deleted properly, I could certainly imagine that eventually github actions runs out of disk space
